#!/bin/sh
echo '用法: aria2c [选项] [统一资源标识符 | 磁力链接 | 种子文件 | 元链接文件]...'
echo '以下打印标记为 #basic 的基础选项。'
echo '输入 aria2c -h#help 可查看所有可用标记分类。'
echo ''
echo '选项:'
echo ' -v, --version                打印版本号并退出。'
echo '                              标记: #basic'
echo ''
echo ' -h, --help[=标记|关键词]     打印使用说明并退出。'
echo '                              帮助信息按标记分类，标记以 "#" 开头。例如，输入 "--help=#http"'
echo '                              可查看标记为 #http 的选项说明。若输入非标记类关键词，将打印'
echo '                              名称包含该关键词的选项说明。'
echo '                              '
echo '                              可选值: #basic（基础）, #advanced（高级）, #http, #https, #ftp, #metalink（元链接）, '
echo '                                     #bittorrent（比特流/BT）, #cookie（Cookie）, #hook（钩子）, #file（文件）, '
echo '                                     #rpc（远程过程调用）, #checksum（校验和）, #experimental（实验性）, '
echo '                                     #deprecated（已废弃）, #help（帮助）, #all（全部）'
echo '                              默认值: #basic'
echo '                              标记: #basic, #help'
echo ''
echo ' -l, --log=日志文件路径       指定日志文件的文件名。若指定为 "-"，日志将输出到标准输出（stdout）。'
echo '                              可选值: /路径/到/文件, -'
echo '                              标记: #basic'
echo ''
echo ' -d, --dir=目录路径           存储下载文件的目录。'
echo '                              可选值: /路径/到/目录'
echo '                              默认值: /data/data/com.termux/files/home（Termux 环境默认）'
echo '                              标记: #basic, #file'
echo ''
echo ' -o, --out=文件名             下载文件的保存名称。该路径始终相对于 -d 选项指定的目录。'
echo '                              当使用 -Z 选项时，此选项将被忽略。'
echo '                              可选值: /路径/到/文件'
echo '                              标记: #basic, #http, #ftp, #file'
echo ''
echo ' -s, --split=数量             使用 N 个连接下载单个文件。若提供的 URI 数量超过 N，前 N 个 URI 会被优先使用，'
echo '                              剩余 URI 作为备用；若提供的 URI 数量少于 N，会重复使用现有 URI 以满足 N 个并发连接。'
echo '                              连接到同一服务器的数量受 --max-connection-per-server 选项限制。'
echo '                              另请参考 --min-split-size 选项。'
echo '                              可选值: 1-*（1 及以上整数）'
echo '                              默认值: 5'
echo '                              标记: #basic, #http, #ftp'
echo ''
echo ' --file-allocation=分配方式   指定文件空间预分配方式。'
echo ''\''none'\'': 不预分配文件空间；'
echo ''\''prealloc'\'': 下载开始前预分配完整文件空间（文件较大时可能耗时）；'
echo '                              若使用新版文件系统（如带扩展区的 ext4、btrfs、xfs 或 NTFS（仅 MinGW 编译版）），'
echo ''\''falloc'\'' 是最佳选择——几乎能瞬间分配大文件（数 GiB）；'
echo '                              请勿在传统文件系统（如 ext3、FAT32）使用 '\''falloc'\''，其耗时与 '\''prealloc'\'' 相近，'
echo '                              且会完全阻塞 aria2 直到分配完成；若系统无 posix_fallocate() 函数，'\''falloc'\'' 不可用；'
echo ''\''trunc'\'': 使用 ftruncate() 系统调用或平台等效接口将文件截断至指定大小。'
echo '                              可选值: none, prealloc, trunc, falloc'
echo '                              默认值: prealloc'
echo '                              标记: #basic, #file'
echo ''
echo ' -V, --check-integrity[=true|false] 验证文件完整性（校验分片哈希或整个文件的哈希值）。'
echo '                              此选项仅对以下场景生效：BT 下载、带校验和的元链接下载、'
echo '                              搭配 --checksum 选项的 HTTP(S)/FTP 下载。'
echo '                              若提供分片哈希，可检测文件损坏部分并重新下载；'
echo '                              若仅提供整个文件的哈希，仅当文件已下载完成（通过文件长度判断）时才校验；'
echo '                              校验失败则从头重新下载；若同时提供分片哈希和文件整体哈希，仅使用分片哈希。'
echo '                              可选值: true, false'
echo '                              默认值: false'
echo '                              标记: #basic, #metalink, #bittorrent, #file, #checksum'
echo ''
echo ' -c, --continue[=true|false]  继续下载未完成的文件。适用于恢复由浏览器或其他“从头顺序下载”的程序'
echo '                              启动的下载任务。目前仅对 http(s)/ftp 下载生效。'
echo '                              可选值: true, false'
echo '                              默认值: false'
echo '                              标记: #basic, #http, #ftp'
echo ''
echo ' -i, --input-file=文件路径    下载文件中包含的 URI。可给单个下载任务指定多个 URI：'
echo '                              在单行中用 TAB 分隔多个 URI；指定为 "-" 时从标准输入读取。'
echo '                              此外，可在每行 URI 后附加选项（该选项行需以一个或多个空格开头，且每行仅一个选项）。'
echo '                              详情见手册页的 INPUT FILE 章节，另请参考 --deferred-input 选项。'
echo '                              可选值: /路径/到/文件, -'
echo '                              标记: #basic'
echo ''
echo ' -j, --max-concurrent-downloads=数量 设置静态 URL（HTTP/FTP）、种子、元链接的最大并发下载数。'
echo '                              另请参考 --split 和 --optimize-concurrent-downloads 选项。'
echo '                              可选值: 1-*（1 及以上整数）'
echo '                              默认值: 5'
echo '                              标记: #basic'
echo ''
echo ' -Z, --force-sequential[=true|false] 按命令行顺序获取 URI，并为每个 URI 启动独立下载会话，'
echo '                              行为与常规命令行下载工具一致。'
echo '                              可选值: true, false'
echo '                              默认值: false'
echo '                              标记: #basic'
echo ''
echo ' -x, --max-connection-per-server=数量 单个下载任务对同一服务器的最大连接数。'
echo '                              可选值: 1-16'
echo '                              默认值: 1'
echo '                              标记: #basic, #http, #ftp'
echo ''
echo ' -k, --min-split-size=大小    当文件分片小于 2*SIZE 字节时，aria2 不会拆分。'
echo '                              示例：下载 20MiB 文件，若 SIZE=10M，可拆分为 [0-10MiB) 和 [10MiB-20MiB) 两个分片，'
echo '                              并使用 2 个源下载（需 --split ≥ 2）；若 SIZE=15M，因 2*15M > 20MiB，'
echo '                              不会拆分，仅用 1 个源下载。'
echo '                              可追加 K 或 M（1K=1024，1M=1024K）。'
echo '                              可选值: 1048576-1073741824（字节，即 1M-1G）'
echo '                              默认值: 20M'
echo '                              标记: #basic, #http, #ftp'
echo ''
echo ' --ftp-user=用户名            设置 FTP 用户名（对所有 FTP URL 生效）。'
echo '                              标记: #basic, #ftp'
echo ''
echo ' --ftp-passwd=密码            设置 FTP 密码（对所有 FTP URL 生效）。'
echo '                              标记: #basic, #ftp'
echo ''
echo ' --http-user=用户名           设置 HTTP 用户名（对所有 HTTP URL 生效）。'
echo '                              标记: #basic, #http'
echo ''
echo ' --http-passwd=密码           设置 HTTP 密码（对所有 HTTP URL 生效）。'
echo '                              标记: #basic, #http'
echo ''
echo ' --load-cookies=文件路径      从文件加载 Cookie（支持 Firefox3 格式、Mozilla/Firefox(1.x/2.x)/Netscape 格式）。'
echo '                              可选值: /路径/到/文件'
echo '                              标记: #basic, #http, #cookie'
echo ''
echo ' -S, --show-files[=true|false] 打印 .torrent、.meta4、.metalink 文件的文件列表并退出；'
echo '                              若为种子文件，将显示更详细信息。'
echo '                              可选值: true, false'
echo '                              默认值: false'
echo '                              标记: #basic, #metalink, #bittorrent'
echo ''
echo ' --max-overall-upload-limit=速度 设置全局最大上传速度（字节/秒）。0 表示无限制。'
echo '                              可追加 K 或 M（1K=1024，1M=1024K）。'
echo '                              若要限制单个种子的上传速度，使用 --max-upload-limit 选项。'
echo '                              可选值: 0-*'
echo '                              默认值: 0'
echo '                              标记: #basic, #bittorrent'
echo ''
echo ' -u, --max-upload-limit=速度  设置单个种子的最大上传速度（字节/秒）。0 表示无限制。'
echo '                              可追加 K 或 M（1K=1024，1M=1024K）。'
echo '                              若要限制全局上传速度，使用 --max-overall-upload-limit 选项。'
echo '                              可选值: 0-*'
echo '                              默认值: 0'
echo '                              标记: #basic, #bittorrent'
echo ''
echo ' -T, --torrent-file=种子文件路径 指定 .torrent 种子文件的路径。'
echo '                              可选值: /路径/到/文件'
echo '                              标记: #basic, #bittorrent'
echo ''
echo ' --listen-port=端口...        设置 BT 下载的 TCP 监听端口。可指定多个端口（用 "," 分隔，如 "6881,6885"），'
echo '                              也可指定端口范围（用 "-" 分隔，如 "6881-6999"），两种分隔符可混用。'
echo '                              可选值: 1024-65535'
echo '                              默认值: 6881-6999'
echo '                              标记: #basic, #bittorrent'
echo ''
echo ' --enable-dht[=true|false]    启用 IPv4 DHT 功能（同时启用 UDP 追踪器支持）。'
echo '                              若种子包含 private 标记，即使设为 true，该种子也不会使用 DHT。'
echo '                              可选值: true, false'
echo '                              默认值: true'
echo '                              标记: #basic, #bittorrent'
echo ''
echo ' --dht-listen-port=端口...    设置 DHT（IPv4、IPv6）和 UDP 追踪器的 UDP 监听端口。'
echo '                              格式同 --listen-port（"," 分隔多端口，"-" 分隔范围）。'
echo '                              可选值: 1024-65535'
echo '                              默认值: 6881-6999'
echo '                              标记: #basic, #bittorrent'
echo ''
echo ' --enable-dht6[=true|false]   启用 IPv6 DHT 功能。'
echo '                              需通过 --dht-listen-port 指定监听端口，另请参考 --dht-listen-addr6 选项。'
echo '                              可选值: true, false'
echo '                              默认值: false'
echo '                              标记: #basic, #bittorrent'
echo ''
echo ' --dht-listen-addr6=地址      指定 IPv6 DHT 套接字绑定的地址（需为主机的全局单播 IPv6 地址）。'
echo '                              标记: #basic, #bittorrent'
echo ''
echo ' -M, --metalink-file=元链接文件路径 指定 .meta4 或 .metalink 元链接文件的路径；指定为 "-" 时从标准输入读取。'
echo '                              可选值: /路径/到/文件, -'
echo '                              标记: #basic, #metalink'
echo ''
echo '=== URI、磁力链接、种子文件、元链接文件 说明 ==='
echo '可指定多个 HTTP(S)/FTP URI。除非使用 -Z 选项，否则所有 URI 必须指向同一文件，否则下载会失败。'
echo '也可指定任意数量的 BT 磁力链接、本地种子文件/元链接文件（这些会被视为独立下载任务）。'
echo ''
echo '可同时通过 -T 选项指定种子文件和 URI：此时会同时从 BT 集群和 HTTP/FTP 服务器下载文件，'
echo '且 HTTP/FTP 下载的数据会上传到 BT 集群。'
echo '对于单文件种子：URI 可为指向资源的完整地址；若 URI 以 "/" 结尾，会自动拼接种子中的 "name" 字段。'
echo '对于多文件种子：会拼接种子中的 "name" 和 "path" 字段，为每个文件生成对应的 URI。'
echo ''
echo '若 URI 包含 "&" 或 shell 中有特殊含义的字符，需用单引号('\'')或双引号(")包裹 URI。'
echo ''
echo '=== 关于连接数的说明 ==='
echo '从 1.10.0 版本开始，aria2 默认对每个主机使用 1 个连接，且分片大小限制为 20MiB。'
echo '因此无论 -s 选项设置多少，每个主机仅使用 1 个连接。若要恢复 1.9.x 版本的行为，'
echo '需设置：--max-connection-per-server=4 --min-split-size=1M。'
echo ''
echo '更多信息请参考手册页（man page）。'